### ISSUE TITLE
请问不懂kotlin但是想要看其中的MVP思想是否可行

### ISSUE THREAD

**Issue by panpeng0014** [nekocode/Murmur#1]

**Comment by nekocode** [comment]
可以选择关注该 [专栏](http://zhuanlan.zhihu.com/kotandroid)。
我近期还会写一篇关于 MVP 设计模式的文章，发布后可以 @ 你一下。

**Comment by panpeng0014** [comment]
非常感谢，虽然没时间学习kotlin，但是mvp是我关注的点
    -依旧在代码的海洋中狗刨

**Comment by nekocode** [comment]
<img width="639" alt="architectrue" src="https://cloud.githubusercontent.com/assets/4783781/14579260/ff4e91e2-03d4-11e6-8f10-a07406be5c93.png">

@panpeng0014 这是我使用 ProcessOn 绘制的一个 MVP 架构图，方便理解。
